### ISSUE TITLE
alpha is missing

### ISSUE THREAD

**Issue by ayl** [hongooi73/glmnetUtils#30]
I am trying to run a very simple logistic regression using cva.glmnet:
`cva.glmnet(out ~ . , data = trainData, family="binomial")`

but I get this error no matter what I do. 

```
Error in match(TRUE, abs(object$alpha - alpha) < 1e-08) :
  argument "alpha" is missing, with no default
Calls: coef -> coef.cva.glmnet -> match
Execution halted
```

**Comment by hongooi73** [comment]
I can't reproduce this problem. Can you provide an example dataset that triggers the error?
