### ISSUE TITLE
Parameters are not being passed to glmnet

### ISSUE THREAD

**Issue by marekpetrik** [hongooi73/glmnetUtils#31]
The function `glmnet.formula` is not forwarding all its parameters to `glmnet`.

See here:
https://github.com/hongooi73/glmnetUtils/blob/5b018681419abe910fff49128109ff40220fcb28/R/glmnetFormula.r#L97

The following parameters are not being passed into the function:
weights=NULL, offset=NULL, subset=NULL,  na.action=getOption("na.action"), drop.unused.levels=FALSE, xlev=NULL, sparse=FALSE, use.model.frame=FALSE, relax=FALSE

Is that deliberate? In case that it is deliberate, it may be useful to mention it in the documentation.

Thanks!

**Comment by hongooi73** [comment]
Those args are ultimately passed to `model.frame` (and its replacement, `makeModelComponents`). In general, don't raise an issue about internal workings of the code. Raise an issue if the code is giving errors or otherwise behaving in an unexpected way.
